### PR TITLE
Fix for IL2CPP link errors on iOS

### PR DESCRIPTION
**Pull request by tomjohnstone**

### CODE REVIEW

**Comment by weeeBox** [comment]
Hello!

Thanks for submitting the request!

All the native methods already marked as OBJC_EXTERN in the lunar_unity_native_interface.h to prevent name mangling: adding this macro into the definition doesn't make a lot of sense.

I've run a few tests and everything seems to be linked fine. What versions of Unity, Xcode and osx do you use?

**Comment by tomjohnstone** [comment]
I'm currently compiling with Unity 5.3.5p3 and Xcode 7.3.1.

I beileve the issue is because IL2CPP locally externs native methods via wrapper functions, rather than via your header so the name mangling directives are lost.

Have you tested IL2CPP rather than using the old Mono runtime?

**Comment by weeeBox** [comment]
Yes, I set "Scripting Backend" to IL2CPP. I'll look more into it.

**Comment by weeeBox** [comment]
I've made a few more tests: everything works fine on my setup (Unity 5.3.5f1 Xcode 7.3). No one has reported it before (the plugin has 2000+ users at this point). Since your proposed changes doesn't do any harm - I'll add them into the next release. Can't really merge this pull request into the master cause it would upset my builder pipeline.

Thanks again for submitting the request and please rate the plugin on Asset Store if you find it useful!

**Pull request closed without merging**
